# Generated by Django 3.1.2 on 2021-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='i_stock',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='i_stock',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='i_stock',
            name='label',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='i_stock',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='i_stock',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='i_stock',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
