# Generated by Django 3.1.2 on 2021-12-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211224_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='User',
            new_name='user',
        ),
    ]
